### ISSUE TITLE
Wrong type arguments error

### ISSUE THREAD

**Issue by freddez** [douo/magit-gptcommit#1]
Hello, I have errors with your plugin. I am using emacs 29.2, last version of gptel and doom emacs.

let: Wrong type argument: (or eieio-object cl-structure-object oclosure), nil

When I call magit-gptcommit-generate

**Comment by douo** [comment]
Thank you for the feedback.  I has no idea about this error. Could you please provide the stack trace by ﻿`(setq debug-on-error t)`?

**Comment by avishefi** [comment]
`magit-gptcommit-generate` currently only works inside a `magit` status buffer.

**Comment by avishefi** [comment]
This should be fixed by #4.

**Comment by avishefi** [comment]
PR #4 is merged, please check and see if this is still relevant.

**Comment by shmul** [comment]
Thanks, though I'm afraid I still get errors.
When trying to call from the magit-status  buffer I get `encode-coding-string: Wrong type argument: symbolp, "user"` . When trying to call from the commit buffer I get ` (or eieio-object cl-structure-object oclosure), nil`. I wonder though whether it should work at all from the commit buffer?

**Comment by avishefi** [comment]
I just tried invoking `magit-gptcommit-generate` from magit status buffer with and without `magit-gptcommig-mode` and it works, I don't see these errors.

The usage of the `user` symbol was removed on the latest version. Do you have the latest version? Can you please provide more details how you invoke?

**Comment by shmul** [comment]
Apologies - upon re-reading the setup instructions I noticed I didn't properly complete the setup. Now I did and it is working fine. Many thanks

**Comment by avishefi** [comment]
Closing this since it seems it is fixed by the new version, please make sure you follow the setup instructions.
